"""empty message

Revision ID: 465ecacb9189
Revises: 73f155245105
Create Date: 2020-03-19 13:39:20.134087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '465ecacb9189'
down_revision = '73f155245105'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
